### ISSUE TITLE
Import of DEA-file fails with errors

### ISSUE THREAD

**Issue by Marko-ilmkreis** [hzi-braunschweig/SORMAS-Project#7962]
### Bug Description

With 1.67.1 the import of the DEA-file fails with an unspecific error.

Here is the used import file (downloaded from DEA, personal data of the persons changed for github)
[Einreiseanmeldungen-2022-01-04 (5).csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/8046820/Einreiseanmeldungen-2022-01-04.5.csv)

The error report:
[sormas_import_error_report.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/8046821/sormas_import_error_report.csv)

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis I suppose that the DEA format has somehow changed. SORMAS reads the birthdate formatted in German (as this was the DEA default when we implemented the importer), e.g. 11.02.2022, but in the file you uploaded, they're specified in a different format (2022-02-11). If that's the case, we need a change request that asks us to alter the way DEA imports are handled.

Can you check whether the import succeeds when you change the date formats?

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis Well, neither the email address, nor the phone number are valid in this file. The specified email address starts with `'=""`, so does the phone number.

**Comment by MateStrysewske** [comment]
Closing this issue because it's been stale for three weeks. @Marko-ilmkreis please let me know if this needs to be reopened.

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske The issue is still there, The  '="",' comes from the original exportfile of DEA.

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis Have you tried to import the file without these characters?

**Comment by Marko-ilmkreis** [comment]
@MateStrysewske Yes, then it works. But in that way every file has to be edited by the desk officer. The ideal would be that they can use it out of the box.

**Comment by MateStrysewske** [comment]
@Marko-ilmkreis Since the format looks VERY strange, I would actually suggest to ask the developers of DEA to provide a CSV that is properly formatted (unless I'm missing something here and this format fulfills some kind of standard). If that's not possible, please get in touch with HZI and discuss this topic; maybe we need a change request then.
