### ISSUE TITLE
The 'Date of Burial' can be set before the 'Date of Birth' if the 'Date of Death' is missing

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#8052]
### Bug Description
On the 'Person' page, if the 'Date of Death' is missing, the 'Date of Burial' can be set before the 'Date of Birth'.

### Steps to Reproduce

1. Open a Person.
2. Set the 'Date of Birth' to 05 April 2019.
3. Set the 'Present condition of person' to 'Buried'
4. Leave the 'Date of Death' empty.
5. Set the 'Date of Burial' to 02 August 2018.
6. Save.

### Expected Behavior
The user shouldn't be able to Save the page and a warning message should appear, informing him accordingly.

### Actual Behavior
The user is able to Save the page even if the 'Date of Burial' is set before the 'Date of Birth'.

### Screenshots
![image](https://user-images.githubusercontent.com/89522688/154657646-d80af970-ca3f-49fa-890a-9fc2f9d343b7.png)

### System Details

* Device: Windows 10
* SORMAS version: 1.68.0
* Android version/Browser: Chrome
* Server URL: test1401.sormas-oegd.de
* User Role: Admin, National User

### Additional Information
Note: When the 'Date of Death' is set, and the user tries to Save the page with a 'Date of Burial' before the 'Date of Death', even if the user cannot Save it, and the warning message appears, the field is not marked red and the exclamation mark is missing. (after a discussion with @MateStrysewske was decided that this 2 issues should be treated together)

![image](https://user-images.githubusercontent.com/89522688/154658781-9d36a2a0-941c-4215-a3b7-9e1030538f14.png)
![image](https://user-images.githubusercontent.com/89522688/154659201-ad9c24ee-6df0-4530-ac81-0baefa1bcce0.png)

**Comment by bernardsilenou** [comment]
- We only validate the dates that are associated (death and burial) and others are taken as error records.
- The date of the report or last contact can also be before the date of birth.
- Would suggest that we only validate with death and burial date

**Comment by dinua** [comment]
First part is fixed in PR https://github.com/hzi-braunschweig/SORMAS-Project/pull/8235
The second part I could not reproduce , when the "Date of burial" is set after the "Date of death" the field for "Date of burial" is marked with red as an error

**Comment by roxanamlendea** [comment]
@dinua Apparently is tricky to reproduce it. I managed to reproduce it by setting the Date of Burial first, and the Date of Death after. Only works in this order. See the recording:
![date of burial](https://user-images.githubusercontent.com/89522688/156751512-9a5a5088-abb8-47f9-bd5b-a425accac34a.gif)

**Comment by adinaflorea9** [comment]
While verifying the ticket, the following behaviors have been observed as well, on the 'Person' page: 

1. The 'Date of death' and 'Date of burial' fields are not highlighted when the date validation is triggered, in the following scenario: the user inputs an invalid date combination between the two fields, but they first input the 'Date of burial' and then the 'Date of death';

2. The 'Date of burial' does not get cleared when the 'Present condition of person' is changed from 'Buried' to 'Dead';

3. The fields: 'Death place type', 'Death place description', 'Burial conductor', 'Burial place description' do not get cleared when the 'Present condition of person' is changed to any of the other values available.

4. The date validation for the fields 'Date of death' and 'Date of burial' does not get cleared when one of them is updated from an invalid combination of dates to a valid one.

5. Age calculation does not get cleared when the 'year-month-day' fields get cleared.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.70.0-SNAPSHOT(cfe1dfb).

I am reopening the ticket as the following behavior is still reproducible: the fields: 'Burial conductor', 'Burial place description' do not get cleared when the 'Present condition of person' is changed to the following values: alive, unknown, empty value in the field.

**Comment by adinaflorea9** [comment]
Verified ticket on the local machine, using the latest version of SORMAS from the development branch - 1.71.0-SNAPSHOT(febce5a).

Verified the mobile app part of the ticket using the https://test.sormas.netzlink.com/sormas-rest/ server, using the SORMAS version 1.70.0.
